name = "ModFest 1.17"
author = "ModFest"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ebc5326e847bbfe247913d5ab89063a2a770c929f2e0aad3e11d961e12affe3"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"
